package com.applicaster.liveswitcher.utils

object Constants {
    const val EXTENSION_START_TIME = "start_time"
    const val EXTENSION_END_TIME = "end_time"
    const val EXTENSION_APPLICASTER_CHANNEL_ID = "applicaster_channel_id"
    const val SIMPLE_DATE_FORMAT = "yyyy-MM-dd'T'HH:mm:ss"
    const val PREFERENCE_ITEM_SELECTED_POSITION = "item_selected_position"

    const val CONF_LIVE_HEADER_TEXT = "ls_live_header_text"
    const val CONF_LIVE_HEADER_TEXT_COLOR = "ls_live_header_text_color"
    const val CONF_LIVE_HEADER_FONTSIZE = "ls_live_header_fontsize"
    const val CONF_LIVE_HEADER_HEIGHT = "ls_live_header_height"
    const val CONF_LIVE_HEADER_BACKGROUND_COLOR = "ls_live_header_background_color"
    const val CONF_NEXT_HEADER_TEXT = "ls_next_header_text"
    const val CONF_NEXT_HEADER_TEXT_COLOR = "ls_next_header_text_color"
    const val CONF_NEXT_HEADER_FONTSIZE = "ls_next_header_fontsize"
    const val CONF_NEXT_HEADER_HEIGHT = "ls_next_header_height"
    const val CONF_NEXT_HEADER_BACKGROUND_COLOR = "ls_next_header_background_color"
    const val CONF_PROGRAM_TITLE_TEXT_COLOR = "ls_program_title_text_color"
    const val CONF_PROGRAM_TITLE_FONTSIZE = "ls_program_title_fontsize"
    const val CONF_PROGRAM_SCHEDULE_TEXT_COLOR = "ls_program_schedule_text_color"
    const val CONF_PROGRAM_SCHEDULE_FONTSIZE = "ls_program_schedule_fontsize"
    const val CONF_WATCHING_TAG_TEXT = "ls_watching_tag_text"
    const val CONF_WATCHING_TAG_TEXT_COLOR = "ls_watching_tag_text_color"
    const val CONF_WATCHING_TAG_TEXT_FONTSIZE = "ls_watching_tag_fontsize"
    const val CONF_WATCHING_TAG_TEXT_BACKGROUND_COLOR = "ls_watching_tag_text_background_color"
    const val CONF_LIVE_EVENT_TAG_TEXT = "ls_live_event_tag_text"
    const val CONF_LIVE_EVENT_TAG_TEXT_COLOR = "ls_live_event_tag_text_color"
    const val CONF_LIVE_EVENT_TAG_FONTSIZE = "ls_live_event_tag_fontsize"
    const val CONF_LIVE_EVENT_TAG_TEXT_BACKGROUND_COLOR = "ls_live_event_tag_text_background_color"
    const val CONF_LIVE_CHANNEL_ICON_HEIGHT = "ls_channel_icon_height"
    const val CONF_LIVE_CHANNEL_ICON_WIDTH = "ls_channel_icon_width"
    const val CONF_BACKGROUND_COLOR = "ls_background_color"
    const val CONF_REMINDER_ASSET_SELECTED = "ls_reminder_asset_selected"
    const val CONF_REMINDER_ASSET = "ls_reminder_asset"
}